name: ecommerce
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter

  get: ^4.7.2
  http: ^1.4.0
  cupertino_icons: ^1.0.8
  carousel_slider: ^5.1.1
  cached_network_image: ^3.4.1
  iconsax: ^0.0.8

  smooth_page_indicator: ^1.2.0+3

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # ===================LOCAL ASSETS====================#
  assets:
    #   - assets\images\onboarding_images\woman_order_now.png
    #   - assets\images\onboarding_images\man_searching_now.png
    #   - assets\images\onboarding_images\man_delivery_now.png
    #   - assets\logos\welcom_logo.png
    #   - assets/logos/3d_google.png
    #   - assets/logos/3d_facebook.png
    #   - assets\images\onboarding_images\man_message_now.png
    - assets\images\tick_success_one.png
    - assets\images\tick_success_two.png
    - assets\images\my_self_img_1.jpg
  #   - assets\images\success_woman_man.png

  # ===================LOCAL FONTS====================#
  # fonts:
  #   - family: Poppins
  #     fonts:
  #       - asset: assets\fonts\Poppins-Light.ttf
  #         weight: 300
  #       - asset: assets\fonts\Poppins-Regular.ttf
  #         weight: 400
  #       - asset: assets\fonts\Poppins-Italic.ttf
  #         style: italic
  #       - asset: assets\fonts\Poppins-Medium.ttf
  #         weight: 500
  #       - asset: assets\fonts\Poppins-MediumItalic.ttf
  #         weight: 500
  #         style: italic
  #       - asset: assets\fonts\Poppins-SemiBold.ttf
  #         weight: 600
  #       - asset: assets\fonts\Poppins-Bold.ttf
  #         weight: 800
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/to/font-from-package
